export const GALLO_CATALOG_OFFERINGS = [
  {
    _id: 'off_gallo_mecanica_general',
    businessSlug: 'gallo',
    name: 'Mecánica general',
    title: 'Mecánica general',
    displayName: 'Mecánica general',
    description: '',
    category: 'mecanica_mantenimiento',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 10,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_mantenimiento_preventivo',
    businessSlug: 'gallo',
    name: 'Mantenimiento preventivo',
    title: 'Mantenimiento preventivo',
    displayName: 'Mantenimiento preventivo',
    description: '',
    category: 'mecanica_mantenimiento',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 20,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_afinamiento',
    businessSlug: 'gallo',
    name: 'Afinamiento',
    title: 'Afinamiento',
    displayName: 'Afinamiento',
    description: '',
    category: 'mecanica_mantenimiento',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 30,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_cambio_aceite',
    businessSlug: 'gallo',
    name: 'Cambio de aceite',
    title: 'Cambio de aceite',
    displayName: 'Cambio de aceite',
    description: '',
    category: 'mecanica_mantenimiento',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 40,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_scanner',
    businessSlug: 'gallo',
    name: 'Scanner',
    title: 'Scanner',
    displayName: 'Scanner',
    description: '',
    category: 'diagnostico_seguridad',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 50,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_sistema_electrico',
    businessSlug: 'gallo',
    name: 'Sistema eléctrico',
    title: 'Sistema eléctrico',
    displayName: 'Sistema eléctrico',
    description: '',
    category: 'diagnostico_seguridad',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 60,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_frenos',
    businessSlug: 'gallo',
    name: 'Frenos',
    title: 'Frenos',
    displayName: 'Frenos',
    description: '',
    category: 'diagnostico_seguridad',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 70,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_suspension',
    businessSlug: 'gallo',
    name: 'Suspensión',
    title: 'Suspensión',
    displayName: 'Suspensión',
    description: '',
    category: 'diagnostico_seguridad',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 80,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_refrigeracion',
    businessSlug: 'gallo',
    name: 'Refrigeración',
    title: 'Refrigeración',
    displayName: 'Refrigeración',
    description: '',
    category: 'diagnostico_seguridad',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 90,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_alineacion_balanceo',
    businessSlug: 'gallo',
    name: 'Alineación y balanceo',
    title: 'Alineación y balanceo',
    displayName: 'Alineación y balanceo',
    description: '',
    category: 'diagnostico_seguridad',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 100,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_planchado',
    businessSlug: 'gallo',
    name: 'Planchado',
    title: 'Planchado',
    displayName: 'Planchado',
    description: '',
    category: 'carroceria_cuidado',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 110,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_pintura',
    businessSlug: 'gallo',
    name: 'Pintura',
    title: 'Pintura',
    displayName: 'Pintura',
    description: '',
    category: 'carroceria_cuidado',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 120,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_detailing',
    businessSlug: 'gallo',
    name: 'Detailing',
    title: 'Detailing',
    displayName: 'Detailing',
    description: '',
    category: 'carroceria_cuidado',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 130,
    active: true,
    publicVisible: true,
  },
  {
    _id: 'off_gallo_autolavado',
    businessSlug: 'gallo',
    name: 'Autolavado',
    title: 'Autolavado',
    displayName: 'Autolavado',
    description: '',
    category: 'carroceria_cuidado',
    verticalType: 'vehicle_service',
    offeringType: 'service',
    displayOrder: 140,
    active: true,
    publicVisible: true,
  },
] as const;
